filter:
    excluded_paths: [client/public/*]

build:
    environment:
        mongodb: '3.2'
    tests:
        override:
            -
                command: 'npm run coverage-scrut'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
