filter:
    excluded_paths: [client/public/*]

build:    
    tests:
        override:
            -
                command: 'nyc --reporter=clover mocha test/test.js'
                coverage:
                    file: 'coverage/clover.xml'
                    format: 'clover'
